### ISSUE TITLE
how to change the navigationManager language of voice ? 

### ISSUE THREAD

**Issue by longlive68** [heremaps/here-ios-sdk-examples#102]
Hello Sir , 
I just wonder how can we change the voice language when we using the navigation .
I saw there is a NMAVoicePackage there , but not for sure . 
Hope can provide some source code for us . 
Thanks so much .

**Comment by dashchak** [comment]
See [Voice Instructions Guide for iOS Premium SDK](https://developer.here.com/documentation/ios-premium/dev_guide/topics/map-voice-instructions.html)

**Comment by longlive68** [comment]
thanks
