### ISSUE TITLE
iOS 13 NMAMapView crash with EXC_BAD_ACCESS (code=1, address=0x18)

### ISSUE THREAD

**Issue by dunqi** [heremaps/here-ios-sdk-examples#111]
Currently the App crashes on init NMAMapView with iOS 13

**Comment by dunqi** [comment]
var mapView = NMAMapView() ---> EXC_BAD_ACCESS (code=1, address=0x18)

Even with new project - only using this view

**Comment by f4st** [comment]
Hello @dunqi,

Thank you for reporting the issue. The iOS 13 is not supported by HERE iOS SDK v3.12, as iOS 13 is not officially released by Apple yet. 
We plan to have iOS 13 support in HERE iOS SDK v3.13 (eta Oct, 2019)

Kind regards,
@f4st

**Comment by dashchak** [comment]
Issue is not reproducible for me on Xcode 11.0 beta 3 (11M362v) (latest at the moment)
1. I am able to run Github sample project using Xcode 11 and iOS 13 device.
2. I am able to run new Single View App project created in Xcode 11 with NMAMapView.

In both cases mapView is drawn. 
It works when mapView was initialized programmatically or added via Storyboard

Checked on macOS 10.14.5. SwiftUI is not used.

**Comment by dunqi** [comment]
Very strange. In both cases (storyboard and by view) it crashed 🤔 but maybe only in simulator? Cause you tested it on real device right?

**Comment by dunqi** [comment]
Okay I installed it on a real device and it didn't crash... so it's maybe just an Xcode Bug :) sorry

**Comment by daehn** [comment]
I'm running into the same issue on iOS 12, crashing with a SIGABRT as soon as I instantiate a `NMAMapView`. Unfortunately there isn't that much information available.

```
libsystem_kernel.dylib`__pthread_kill:
    0x1168752bc <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x1168752c1 <+5>:  movq   %rcx, %r10
    0x1168752c4 <+8>:  syscall 
->  0x1168752c6 <+10>: jae    0x1168752d0               ; <+20>
    0x1168752c8 <+12>: movq   %rax, %rdi
    0x1168752cb <+15>: jmp    0x11686f457               ; cerror_nocancel
    0x1168752d0 <+20>: retq   
```
