### ISSUE TITLE
What is the iOS corresponding to Java´s onMapObjectsSelected Gesture Event?

### ISSUE THREAD

**Issue by oli06** [heremaps/here-ios-sdk-examples#112]
In Java´s SDK version there is a method called 
```java
boolean onMapObjectsSelected(java.util.List<ViewObject> objects)
```
(https://developer.here.com/documentation/android-starter/api_reference_java/com/here/android/mpa/mapping/MapGesture.OnGestureListener.html).

Is there a corresponding iOS implementation?

All I can find is 
```objective-c
-(void)mapView:(NMAMapView *)mapView didReceiveTapAtLocation:(CGPoint)location
```
 to handle tapEvents. (https://developer.here.com/documentation/ios-premium/dev_guide/topics/map-gestures.html) 

How could I implement such a behavior on my own?

Thanks!

**Comment by dashchak** [comment]
For iOS you can use [NMAMapViewDelegate:](https://developer.here.com/documentation/ios-premium/api_reference_jazzy/Protocols/NMAMapViewDelegate.html#%2Fc:objc(pl)NMAMapViewDelegate(im)mapView:didSelectObjects:)
`- (void)mapView:(nonnull NMAMapView *)mapView didSelectObjects:(nonnull NSArray<NMAViewObject *> *)objects`

Or use **location** from _didReceiveTapAtLocation:(CGPoint)**location**_ in [NMAMapView:](https://developer.here.com/documentation/ios-premium/api_reference_jazzy/Classes/NMAMapView.html)
```
- (nonnull NSArray<NMAViewObject *> *)objectsAtPoint:(CGPoint)point;
- (nonnull NSArray<NMAViewObject *> *)visibleObjectsAtPoint:(CGPoint)point;
```

**Comment by oli06** [comment]
Thank @dashchak ,
did not see this in the first place.
