### ISSUE TITLE
Code signing "NMAKit.framework" failed.

### ISSUE THREAD

**Issue by fabiancarlos** [heremaps/here-ios-sdk-examples#113]
When i try to release the app, with archive, i tried everything... and i receing this...

`
Code signing "NMAKit.framework" failed.
`

![Screen Shot 2019-07-17 at 3 42 05 PM](https://user-images.githubusercontent.com/636804/61406280-853fc880-a8a9-11e9-8b94-c51e0c1b0db4.png)

**Comment by dashchak** [comment]
Hi @fabiancarlos, could you please specify more details? 
i.e. What Xcode and NMAKit versions you use? Are you archiving sample Github project or your own one?
Can you share logs from Show Logs button on your screenshot?

**Comment by fabiancarlos** [comment]
hey... i fixed that when run the file .sh on the folder close to the framework lib.

**Comment by dashchak** [comment]
Correct, if you open **strip_sim.sh** in any text editor, you will notice its purpose: 

> This script can be used to strip the simulator specifc architectures from the NMAKit library.
> The simulator architectures must be removed from NMAKit before it is included in an app which
> will be uploaded to the Apple Store.
