### ISSUE TITLE
Please help me to use map-matching sdk

### ISSUE THREAD

**Issue by tiny0101** [heremaps/here-ios-sdk-examples#114]
Dear support team of Here Map SDK.

I have read your guide about map-matching.

https://developer.here.com/documentation/ios-premium/dev_guide/topics/map-matching.html

I really want to use map-matching apis.
I am going to draw my movement onto the road while driving.
**At this time, I don't specify the destination.**
However, because of the GPS coordinate error, I couldn't draw the correct path on the map. It often crosses buildings and is drawn onto unexpected location.
I am so excited to visit the above topic.

However, I couldn't see any method how to use map-matching apis.
Please offer simple demo code for the map-matching.

**Comment by dashchak** [comment]
Hi @tiny0101, 
please check [NMAPositioningManager](https://developer.here.com/documentation/ios-premium/api_reference_jazzy/Classes/NMAPositioningManager.html#%2Fc:objc(cs)NMAPositioningManager(py)mapMatchedPosition) API. 
```
NMAPositioningManager *positioningManager = [NMAPositioningManager sharedPositioningManager];

// Register to positioning manager notifications
 [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(positionDidUpdate) name:NMAPositioningManagerDidUpdatePositionNotification object:positioningManager];

if ([positioningManager startPositioning]) {
    positioningManager.mapMatchingEnabled = YES;
    positioningManager.mapMatchMode = NMAMapMatchModeCar;
    [positioningManager.dataSource setBackgroundUpdatesEnabled:YES];
}

// Handle NMAPositioningManagerDidUpdatePositionNotification 
- (void)positionDidUpdate{
    NMAGeoPosition *position = positioningManager.mapMatchedPosition;
}
```

**Comment by tiny0101** [comment]
Thanks, @dashchak.
I am going to check.

**Comment by starand** [comment]
@tiny0101 did you solve your issue? Can we close this one?
