### ISSUE TITLE
Crash when creating a NMAMapView

### ISSUE THREAD

**Issue by daehn** [heremaps/here-ios-sdk-examples#118]
We're trying to integrate the Here SDK but are experiencing `SIGABRT` crashes when instantiating a `NMAMapView`. I know that this works in your sample project so I assume there are some other configuration differences. 

```
libsystem_kernel.dylib`__pthread_kill:
    0x1168752bc <+0>:  movl   $0x2000148, %eax          ; imm = 0x2000148 
    0x1168752c1 <+5>:  movq   %rcx, %r10
    0x1168752c4 <+8>:  syscall 
->  0x1168752c6 <+10>: jae    0x1168752d0               ; <+20>
    0x1168752c8 <+12>: movq   %rax, %rdi
    0x1168752cb <+15>: jmp    0x11686f457               ; cerror_nocancel
    0x1168752d0 <+20>: retq   
```

After researching a bit this seems to be a common issue (see [this Twitter thread](https://twitter.com/aveapps/status/1167079026319613952?s=20) for example).
I'm currently in the process of capturing more logs, but please let me know what kind of other information you'd need in order to debug this.

**Comment by dashchak** [comment]
Could you please provide code sample with your Here SDK configurations causing crash? Also, please specify Xcode and device versions.

**Comment by daehn** [comment]
Xcode 10.3 (10G8)
Running on iPhone Simulator XR 12.4 (also happens on device though)
Using HereSDK  3.12.2 (also happens with previous versions)

We're setting up the SDK in our AppDelegate and the crash happens when creating the first `NMAMapView`:

<img width="630" alt="Screenshot 2019-08-30 at 10 19 58" src="https://user-images.githubusercontent.com/4603353/64005024-c6193700-cb0f-11e9-937e-5fa9c90557ef.png">

I can't share our complete project here but I will try to create a sample project that reproduces this issue. Are there any other necessary steps in order for the SDK to work correctly (e.g. some plist values being present etc.)?

**Comment by dashchak** [comment]
Do you use CocoaPods or manually adding NMAKit.framework? Do you get any console error when crash happens? 
Regarding configuration, make sure you set your credentials(appID, appCode, licenseKey) before accessing NMAMapView

**Comment by daehn** [comment]
We're using CocoaPods and I'm seeing a console error now which explains the issue (we had disabled other logs using `OS_ACTIVITY_MODE`).

```
*** NMAKit FATAL: License Key, App ID, or App Code not set.
```

So I assume something is wrong with out configuration. Thanks a lot for the help!

**Comment by daehn** [comment]
On that note: I would expect a crash caused by a wrong configuration of the SDK to happen when configuring the SDK in the AppDelegate instead of when instantiating a map view.
