### ISSUE TITLE
Swift guides coming soon?

### ISSUE THREAD

**Issue by dbabbs** [heremaps/here-ios-sdk-examples#12]

**Comment by JH-YVR** [comment]
A dedicated guide for Swift is not on the immediate horizon however you should see ongoing updates to the SDK to better support Swift developers and that includes more Swift examples.

**Comment by RPGII** [comment]
Yep, more examples would be very good.

**Comment by rajaseenivasan8989** [comment]
NMANavigationDelegates not getting fired in swift

**Comment by tlushney** [comment]
Several swift samples have been already added. We plan to port all samples to swift in near future. Swift version of API references will be available starting for next release.
