### ISSUE TITLE
Navigation Voice speed adjust

### ISSUE THREAD

**Issue by moment101** [heremaps/here-ios-sdk-examples#126]
I wanna change the speed of voice, Is there any parameter to adjust the speed ?

The following document is a synthesis of a sentence and then adjust the speed of speech, but it is a little complicated. 
https://developer.here.com/documentation/ios-premium/api_reference_jazzy/Classes/NMATTSAudioOutput.html#%2Fc:objc(cs)NMATTSAudioOutput(py)speechRate

**Comment by dashchak** [comment]
Hi, 
there is no public API to change the speech rate during Guidance in iOS SDK.
Android SDK [does have it](https://www.developer.here.com/documentation/android-premium/api_reference_java/com/here/android/mpa/guidance/NavigationManager.AudioPlayer.html).

You still can achieve it in iOS by listening to navManager callbacks.
Catch the moment when voice guidance instruction is about to play, then customize it and play:

```
- (BOOL)navigationManager:(nonnull NMANavigationManager *)navigationManager
    shouldPlayVoiceFeedbackWithText:(nullable NSString *)text
{    
    NMATTSAudioOutput *output = [NMATTSAudioOutput audioOutputWithText:text];
    output.speechRate = AVSpeechUtteranceDefaultSpeechRate / 4.0f;  //4 times slower than by default
    [[NMAAudioManager sharedAudioManager] playOutput:output];

    return NO;  // Since we played it, prevent play it again by navManager
}
```

**Comment by moment101** [comment]
@dashchak Got it!! Thanks for your advice.
