### ISSUE TITLE
Transit routing estimate time

### ISSUE THREAD

**Issue by moment101** [heremaps/here-ios-sdk-examples#127]
Hi HERE,

We use mobile SDK to get transit routing, and have encountered some issues would like to ask you.

1. Wait bus/train time

Start time 3:00, walk 10 min to bus stop, and the bus start at 3:15. Is this 5 min waiting included in total travel time??

 I used several times to get public transit routing.

3:00 ----- (10 min walk) --------3:10(bus stop)  ------ (20 min travel time)------3:30 arrive
3:05 ----- (10 min walk) --------3:15(bus stop)  ------ (20 min travel time)------3:35 arrive
3:10 ----- (10 min walk) --------3:20(bus stop)  ------ (20 min travel time)------3:40 arrive

But the bus departure time interval is more than 10 min, you can never arrive the bus stop and just got the bus coming.

Is there any SDK API or parameter setting for get real bus departure time and include the waiting time?  In order to get more accurate time estimate, those are better to be considered.

2. bus arrive / departure time

Some vehicles will wait for a while before starting. Is the time from SDK transit routing arrive time or departure time??

Best regards,

Jon Chiang

**Comment by dashchak** [comment]
Hi @moment101  
1. Unfortunately there is no such kind of API. If PT provider gives us such info, it is automatically included in route tta. 
2. Arrival time is calculated based on departure time + estimated route time, which might include traffic conditions, etc
