### ISSUE TITLE
Unexpected Marker/Polyline behaviour

### ISSUE THREAD

**Issue by marcomilov** [heremaps/here-ios-sdk-examples#130]
Hi all,
I'm currently experiencing some weird issues with markers and polylines. When placing a marker on the current user position and adding a dashed polyline to a specific destination, they can be moved by scrolling the mapview. This does not happen with the marker at the destination. Furthermore, they positions align when positioning in the middle of View.  I already played around with the transformCenter property without any success.
I have attached a screenrecord that shows the unexpected behaviour. Any help in this regard would be highly appreciated, since this issue is bugging me for days.

![HereMaps_Polybug (7)](https://user-images.githubusercontent.com/29037354/67669153-9e104d80-f971-11e9-842b-bff45d0a40a7.gif)

**Comment by marcomilov** [comment]
Finally fixed it! The problem was that I did not the altitude of the geocoordinate into consideration. Since I use the user position, the marker and polyline have an altitude, which lead to the behaviour

**Comment by NasrullahKhan** [comment]
@marcomilov how you're drawing dashed polyline in iOS. i found nothing related to dashed polyline in documentation.

Please share the code snippet and documentation link if you can. 

Thanks
