### ISSUE TITLE
Navigation Map Swing

### ISSUE THREAD

**Issue by moment101** [heremaps/here-ios-sdk-examples#133]
When driving straight forward on the road, the map always lean left and right randomly. See attached file.  (simulation and real driving both show swing)  

At the turn, the swing is more obvious.
The direction of the vehicle sign is unstable. It randomly sway to other directions instead of going straight. One severe scenario is when I turn left at the intersection, it shows I turn 180 degree.

How to stop the swing ?? Thanks.

sdk version 3.13
mapTrackingEnable = true
mapTrackingAutoZoomEnable = true
mapTrackingOrientation = .dynamic

[620-2.MOV.zip](https://github.com/heremaps/here-ios-sdk-examples/files/3782695/620-2.MOV.zip)

let marker = NMAMapMarker.init(geoCoordinates: location.transformToNMACoordinate(), icon: NMAImage.init(uiImage: markerImage)!)       
mapView.positionIndicator.displayObject = marker

**Comment by moment101** [comment]
[IMG_7214.TRIM (1).MOV.zip](https://github.com/heremaps/here-ios-sdk-examples/files/3782729/IMG_7214.TRIM.1.MOV.zip)

If I can drift  ：）

**Comment by dashchak** [comment]
Hi @moment101,  sorry for delay. Looking.
Is it reproduced with default indicator as well?

**Comment by moment101** [comment]
Hi @dashchak ,
Yes, it is default indicator. I just replaced the image.

let marker = NMAMapMarker.init(geoCoordinates: coordinate, icon: NMAImage.init(uiImage: markerImage)!)
mapView.positionIndicator.displayObject = marker

**Comment by dashchak** [comment]
I mean if you keep the default image, is it also reproduced? 
Please also specify the map scheme you use, if it is not the default one.

**Comment by dashchak** [comment]
Yes, I can reproduce it. Will let you know when root cause is found and fix is planned for release.

**Comment by moment101** [comment]
If I use default image, the swing is also happen. 
NMAMapSchemeCarNavigationDayWithTraffic and NMAMapSchemeCarNavigationNightWithTraffic are used for map scheme.

Thanks for helping, I have struggled in this for two months.

**Comment by dashchak** [comment]
I have found the root cause. 
It is only reproduced when course changes from 359° to 1° or vice versa. 0° is North. 
The course delta is calculated not as a minimum one (2°) but as a difference (359° - 1° = 358°).
As a result our interpolation algorithm produces wrong guesses. 

The fix is in testing now. It is planned to be added to next HERE SDK release (3.14.2).
The expected release date is December 20.

Thanks for reporting!

**Comment by moment101** [comment]
Thanks @dashchak , I close this issue first. Look forward the new version.
