### ISSUE TITLE
Error Publishing to App Store

### ISSUE THREAD

**Issue by sailendra85** [heremaps/here-ios-sdk-examples#134]
I have an rejection to using this library, it is ITMS- 90338 as emailed by Apple, anyone have same issue like me, if so please let me know how to resolved it

**Comment by starand** [comment]
Hi @sailendra85,
Which SDK version do you use? Last Monday we released 3.13 SP1 SDK, which includes fixes for uploading to AppStore. Please got to dev portal and download fresh version of SDK.

**Comment by dashchak** [comment]
Please update HERE Maps SDK to 3.13.3. 
See details:
https://stackoverflow.com/questions/58214571/ios-here-sdk-nmakit-private-api-usage
