### ISSUE TITLE
Cannot upload new layer using API

### ISSUE THREAD

**Issue by nitrochaien** [heremaps/here-ios-sdk-examples#135]
I use this url to upload new layer
`https://cle.api.here.com/2/layers/upload.json?layer_id=1&file=ID%09NAME%09WKT%0AAA%09nam_te%73t%09LINESTRING%28105.805389 20.999508%2C105.805165 20.99895%29&app_id={app_id}&app_code={app_code}`

Response is
```
{
    "storedTilesCount": 1,
    "response_code": "201 Created"
}
```
Which is okay.

However, I continue to call this API with the same layer_id:
`https://cle.api.here.com/2/search/proximity.json?layer_ids=1&proximity=20.999508,105.805389,200&app_code={app_code}&app_id={app_id}`

Response is:
```
{
    "issues": [
        {
            "message": "No layer or no layer covering the area found"
        }
    ],
    "error_id": "05f8a41a-6cb4-4c21-82a4-4a94c35017ce",
    "response_code": "400 Bad Request"
}
```
Is that because the upload.json API did not upload a new layer?
What was I wrong here?

Thank you.

**Comment by starand** [comment]
Hi @nitrochaien,
This is wrong project to report json related issues.
This project is for reporting issues on iOS Mobile SDK (where we do not work directly with  json files, but ObjectiveC/Swift API).
