### ISSUE TITLE
Navigation turn by turn engine didn't start or stop not to work

### ISSUE THREAD

**Issue by moment101** [heremaps/here-ios-sdk-examples#136]
According to document (https://developer.here.com/documentation/ios-premium/dev_guide/topics/map-guidance.html), when user is far from a road, turn by turn navigation may not start immediately. 

But sometimes, user followed the route for a while (on the road), the navigation still didn't start.

![Headtonearestroad1 (1)](https://user-images.githubusercontent.com/5095177/68923700-df9a5880-07b9-11ea-80a9-027e65ef4b48.jpg)

And sometimes, the navigation engine start at the beginning, but suddenly it stopped working and never to wake again.

![noupdate405 (1)](https://user-images.githubusercontent.com/5095177/68923713-e5903980-07b9-11ea-9336-f85e15c2adf9.jpg)

How to handle these kind of situations? Is there any callback can be used for reset navigation manager  engine ?? Thanks.

**Comment by Merlin1stHere** [comment]
We need more information to reproduce this issue. It seems the device couldn't get accurate location. In this case navigation couldn't start or may be suspended. Could you please provide the gpx log, taken when this issue occurs?

**Comment by moment101** [comment]
Hi @Merlin1stHere ,
We didn't have the gpx log, we will start to implement this feature. 
I have a question, from above pictures, the arrow marker is the position of user. So I think the system should have the location of user. Do you mean that the location is not accurate enough?

**Comment by Merlin1stHere** [comment]
Hi @moment101,
I mean https://developer.android.com/reference/kotlin/android/location/Location.html#getAccuracy().
Sometimes, due to network conditions, the system updates the location very rarely and with very inaccurate values.

**Comment by starand** [comment]
@moment101 did you solve the issue?

**Comment by moment101** [comment]
@starand Not yet, I don't know how and when to reset navigation engine if it didn't start or  suspend.

**Comment by Merlin1stHere** [comment]
@moment101 Navigation should start or continue automatically when device get accurate position (from GPS). Location updates from the mobile network or WiFi aren't used for navigation.

**Comment by starand** [comment]
@moment101 any progress on the issue?

**Comment by moment101** [comment]
@starand No. I only show "GPS signal is very inaccurate" on navigation view. I don't know how to deal with these situation.
Above two pictures, you can see the position indicator was changed, is it due to the poor accurate that navigation didn't start??

**Comment by starand** [comment]
I do not see any change in position indicator. What do you mean?
May be PositionIndicator.setAccuracyIndicatorVisible(true) can help

**Comment by moment101** [comment]
We did setAccuracyIndicatorVisible(true), but those two picture above didn't show. I guess the GPS signal were very poor at that time.

**Comment by starand** [comment]
@moment101, we are going to release SDK 3.14 about 23rd of Dec. There should be included few improvements regarding positioning. Probably that can improve the case.
We are still waiting for GPX logs.

**Comment by moment101** [comment]
@starand Thanks for help. We are looking forward the new version. If we can get the GPX logs at those situation, we will provide asap.
