### ISSUE TITLE
navigationManager didFindAlternateRoutes not firing

### ISSUE THREAD

**Issue by fadijabi** [heremaps/here-ios-sdk-examples#137]
Hello,

navigationManager didFindAlternateRoutes was working fine for us until we upgraded to v3.13.3. Now it is not firing for us after we upgraded to v3.13.3. 

Note that we have not changed any code. The same issue is happening for Android.

Please advise?

**Comment by Merlin1stHere** [comment]
@fadijabi Thanks for feedback! This issue will be fixed in the next release of the SDK.
