### ISSUE TITLE
Re-Routing like google map.

### ISSUE THREAD

**Issue by VivekVithlani** [heremaps/here-ios-sdk-examples#139]
Hello,

I need to re-routing route like google map.
Example: User traveling "Location A"  to  "Location B" in between users takes the wrong turn, then we need to re-routing from current location to destination like google map.

Thank you,
Vivek Vithalani.

**Comment by starand** [comment]
Hi @VivekVithlani, 

Which version of SDK do you use?
Rerouting is done automatically by SDK when user deviates from created route for significant distance.

**Comment by VivekVithlani** [comment]
Thank you for reply to my question.

I am using 3.12.2.83 Version of iOS SDK.

Yes, I checked **navigationManagerWillReroute** but it is only to avoid traffic re-routing which is mentioned in [Traffic-Aware Navigation](https://developer.here.com/documentation/ios-premium/dev_guide/topics/map-guidance-traffic-avoidance.html).

But I don't want to re-route for **Traffic-aware navigation**, I want to re-route when the user take the wrong turn from the current route.

**Comment by VivekVithlani** [comment]
> Hi @VivekVithlani,
> 
> Which version of SDK do you use?
> Rerouting is done automatically by SDK when user deviates from created route for significant distance.
> See **navigationManagerWillReroute** and **navigationManager:didRerouteWithError** in **NMANavigationManager** class.

Thank you for reply to my question.

I am using 3.12.2.83 Version of iOS SDK.

Yes, I checked **navigationManagerWillReroute** but it is only to avoid traffic re-routing which is mentioned in [Traffic-Aware Navigation](https://developer.here.com/documentation/ios-premium/dev_guide/topics/map-guidance-traffic-avoidance.html).

But I don't want to re-route for **Traffic-aware navigation**, I want to re-route when the user take the wrong turn from the current route.

**Comment by dashchak** [comment]
Hi @VivekVithlani.
Traffic avoidance is disabled by default. Check its documentation:
```
/**
 * Sets the navigation traffic avoidance behaviour.
 *
 * If the traffic avoidance mode is dynamic, the navigation manager will
 * automatically update the guidance route to avoid traffic events.
 *
 * If the traffic avoidance mode is manual, the navigation manager delegate will
 * be prompted when a faster route is found and have the option to accept or
 * reject it.
 *
 * Traffic avoidance is disabled by default.
...
- (NMANavigationError)setTrafficAvoidanceMode:(NMATrafficAvoidanceMode)mode;
```
It means, it will not trigger re-routing due to traffic changes unless you explicitly set it to **NMATrafficAvoidanceDynamic**.

Re-routing will automatically be triggered not on wrong user turn but after some deviation from the initial route. Note, deviation differs for Pedestrian and Car routes. 
If you want to show new recalculated route on the map, you need to listen to **didUpdateRouteWithResult:**. Then create new NMAMapRoute based on the result and present it on the map.

**Comment by VivekVithlani** [comment]
> didUpdateRouteWithResult

Ok, I'll try with **didUpdateRouteWithResult** and let you know.

Thank you for your help.

**Comment by VivekVithlani** [comment]
@dashchak Re-Routing will automatically trigger, not calling when the user takes the wrong turn.

Any way to trigger Re-Routing when the user takes the wrong turn?

**Comment by dashchak** [comment]
Unfortunately there is no public API to force it.
We have complicated algorithm for triggering reroute. 
Could you please share any example? i.e the NMARoute you use + positioning traces and the place you expect rerouting.

**Comment by VivekVithlani** [comment]
I wrote the GPX file code which is used for my app.

Search route with Mississauga to Markham and select route via highway 403 to 410 to 407
And try to run with **GPS** turn by turn and select below GPX file.

In this GPX file, I have route is **Mississauga to Brampton to Markham**.

When you select GPX file then the user goes to **Brampton** not go to **Markham**, then we need to re-routing the current location to Markham.


GPX File code
```
<?xml version="1.0"?>
<gpx version="1.1" creator="gpxgenerator.com">
    <wpt lat="43.59963943396963" lon="-79.64266792794069">
        <ele>160.98</ele>
        <time>2019-12-02T11:23:51Z</time>
    </wpt>
    <wpt lat="43.65282190808118" lon="-79.71648232003054">
        <ele>203.48</ele>
        <time>2019-12-02T11:47:08Z</time>
    </wpt>
    <wpt lat="43.72531274178361" lon="-79.67459694405397">
        <ele>180.65</ele>
        <time>2019-12-02T12:11:23Z</time>
    </wpt>
    <wpt lat="43.78334147143159" lon="-79.53726784249147">
        <ele>190.91</ele>
        <time>2019-12-02T12:46:52Z</time>
    </wpt>
    <wpt lat="43.797000285288014" lon="-79.4867609520901">
        <ele>189.26</ele>
        <time>2019-12-02T12:58:53Z</time>
    </wpt>
    <wpt lat="43.82053751694032" lon="-79.476117946719">
        <ele>209.08</ele>
        <time>2019-12-02T13:06:31Z</time>
    </wpt>
    <wpt lat="43.839360624006034" lon="-79.41466317376978">
        <ele>210.50</ele>
        <time>2019-12-02T13:21:23Z</time>
    </wpt>
    <wpt lat="43.838370082157994" lon="-79.36694131097681">
        <ele>184.71</ele>
        <time>2019-12-02T13:32:01Z</time>
    </wpt>
    <wpt lat="43.8767415510838" lon="-79.3775843163479">
        <ele>207.02</ele>
        <time>2019-12-02T13:44:06Z</time>
    </wpt>
</gpx>
```

**Comment by DmytroLytvynovskyi** [comment]
Hi @VivekVithlani 
If I understand correctly you have a route like:
![possible_route](https://user-images.githubusercontent.com/23171614/70620581-53484d80-1c20-11ea-83ef-529f9e88b274.PNG)
and the user goes like that:
![actual_route](https://user-images.githubusercontent.com/23171614/70620595-5fcca600-1c20-11ea-931c-ef0e09e6cf83.PNG)
am I right?
Do you use GPX file above for simulation as is, or it's some short version?

I've tried to simulate deviation as shown in the picture above and re-routing was triggered

**Comment by VivekVithlani** [comment]
Yes, you are right for re-routing as explain above scenario.

Very very thank you for suggesting to me and you try to understand my issue.

I found a solution for re-routing as per given instruction, which is **'didUpdateRouteWithResult'**.

I found a new route in the **'didUpdateRouteWithResult'** method.
