### ISSUE TITLE
NMAMapMarker memory leak in 3.13.3

### ISSUE THREAD

**Issue by libec** [heremaps/here-ios-sdk-examples#141]
Hi, I'm using `NMAMapMarker` to display points of interest on map. On each map movement I remove old ones and add new ones, I noticed that memory spikes when we started using 3.13.3 version to that point that the app get `Terminated due to memory issue`.
I managed to isolate the issue to creation of `NMAMapMarker`. It doesn't even need to be used or displayed on `NMAMapView` to manifest itself. I created [sample project](https://github.com/libec/HereMapsDemo) which demonstrates this behaviour where you can see memory issues with SDK 3.13.3. You just need to move the map around for a bit to call `mapViewDidEndMovement`. If you switch back to 3.12.2 it looks like the marker is released properly and the app never crashes. Is this a known issue?

**Comment by starand** [comment]
@libec thank you for reporting. We will take a look.

**Comment by SiriUS2551AK** [comment]
Hello @libec,

Thank you for reporting the issue.

This issue should be fixed in HERE SDK for iOS v3.14.

The release with the fix is expected on 23 December.
