### ISSUE TITLE
https://github.com/heremaps/here-ios-sdk-examples/tree/master/map-attribute-swift returns 404

### ISSUE THREAD

**Issue by boriguen** [heremaps/here-ios-sdk-examples#142]
Note this link is referred in HERE Developer Portal in this section - https://developer.here.com/documentation/ios-premium/dev_guide/topics/map-schemes.html

**Comment by boriguen** [comment]
Well, the desired example is at https://github.com/heremaps/here-ios-sdk-examples/tree/master/map-attribute-ios-swift instead so this is a Developer Portal bug. Closing this ticket.

**Comment by starand** [comment]
Hi @boriguen,

Thank you for reporting. The issue should be fixed together with SDK 3.14 release (about Dec 23).
