### ISSUE TITLE
WKWebView was invalidated

### ISSUE THREAD

**Issue by kumarrajnees** [heremaps/here-ios-sdk-examples#145]
The camera view remains black and the console through the error
`-[HACIOSPlatformCallsImpl getBrowserUserAgent]_block_invoke:193 - evaluateJavaScript error : The WKWebView was invalidated`

I'm implementing LiveSight feature as documented.
https://developer.here.com/documentation/ios-premium/dev_guide/topics/ar.html

Can you provide me any solution or reason behind this issue?

**Comment by dashchak** [comment]
Hi, could you please specify HERE SDK, iOS versions and device model.

**Comment by dashchak** [comment]
I can reproduce the issue. Please ignore the error. It is not iOS error but one of our 3rd party analytics lib.
It won't affect functionality at all as it only affects analytics getBrowserUserAgent name.
It is planned to be fixed in next 3.15 Release. 
Thanks for reporting!

**Comment by dashchak** [comment]
@kumarrajnees is there any other console warning or error? 
If not, please share your sample code and environment.

**Comment by dashchak** [comment]
We have found and fixed deadlock in AR. Reproduced on iOS 13 devices only. 
AR deadlock as well as WKWebView console error fixes will be available in 3.15 release.
