### ISSUE TITLE
How to show actual travel coordinates route?

### ISSUE THREAD

**Issue by VivekVithlani** [heremaps/here-ios-sdk-examples#146]
Hello,

I need to show the route as per user travel coordinates.

Example
The original route is **Point-A** -> **Point-B** -> **Point-C** coordinate,
then User travel **Point-A** -> **Point-C** -> **Point-B** coordinate.

How to show the route via **Point-A** -> **Point-C** -> **Point-B** coordinate. (User actual travel route).

When I finish the trip in  UBER application then UBER shows the original travel route not show google suggested route.

Thank you.
Vivek Vithalani.

**Comment by Merlin1stHere** [comment]
@VivekVithlani The SDK doesn't have such functionality.
As workaround you can log user coordinates by using [NMAPositioningManager](https://developer.here.com/documentation/ios-premium/api_reference_jazzy/Classes/NMAPositioningManager.html#%2Fc:objc(cs)NMAPositioningManager(py)logType) and then load log using [NMALoggedPositionSource](https://developer.here.com/documentation/ios-premium/api_reference_jazzy/Classes/NMALoggedPositionSource.html) and create polyline from points.

**Comment by VivekVithlani** [comment]
Thank you for your help,

I'll check it in **NMALoggedPositionSource**
