### ISSUE TITLE
Add NMAMapLabeledMarker in NMAClusterLayer

### ISSUE THREAD

**Issue by VivekVithlani** [heremaps/here-ios-sdk-examples#151]
Hello,

Application crash while I try to Add **[NMAMapLabeledMarker](https://developer.here.com/documentation/ios-premium/api_reference_jazzy/Classes/NMAMapLabeledMarker.html)** in **[NMAClusterLayer](https://developer.here.com/documentation/ios-premium/api_reference_jazzy/Classes/NMAClusterLayer.html)**.

**Sample Code**
```
NMAMapLabeledMarker *marker = [NMAMapLabeledMarker mapLabeledMarkerWithGeoCoordinates:[placeLink position] icon:img];
[marker setText:placeLink.name forLanguage:[[NSLocale preferredLanguages] objectAtIndex:0]];

if (self->clusterLayerMarker != nil && self->clusterLayerMarker.markers.count > 0) {
    [self->mapView addClusterLayer:self->clusterLayerMarker];
}
```

Thank you,
Vivek Vithalani.

**Comment by starand** [comment]
Hi @VivekVithlani,

Thank you for reporting. That should be fixed in SDK 3.15. Approximate release date is 1st of Apr.
