### ISSUE TITLE
Here Map Premium sdk with SwiftUi

### ISSUE THREAD

**Issue by bdushi** [heremaps/here-ios-sdk-examples#153]
I ma try to use Here Map Premium sdk with SwiftUi, but I get this error: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

**Comment by bdushi** [comment]
https://stackoverflow.com/questions/58870090/heremaps-with-swiftui-crashes-with-exc-bad-instruction-upon-instantiation

**Comment by starand** [comment]
https://stackoverflow.com/a/59942718/6866440

**Comment by bdushi** [comment]
No, this did not halp me, I am try to create an Instance of HereMap Premium Sdk using SwiftUi not through StroyBoard: NMAMapView mapView = NMAMapView(frame: self.view.frame)

**Comment by dashchak** [comment]
Hi, @bdushi 
Indeed, issue is reproduced with latest NMAKit. Starting investigation.

Thanks for reporting!

**Comment by dashchak** [comment]
I have found the root cause. Fix will be included in next HERE SDK Release(3.15) which is planned on April 1, 2020.
