### ISSUE TITLE
Navigation crashes in NMAKit

### ISSUE THREAD

**Issue by munish-techindustan** [heremaps/here-ios-sdk-examples#154]
We are using **Here map Premium SDK** and implemented live navigation in our app. We are facing some crashes in app and could not recognise the crashes.
We have integrated Firebase Crashlytics which helps us to show crashes in app and we are getting these crashes due to NMAKit.
1. Crashed: com.here.networks.HttpClientSessionQueue (QOS: UNSPECIFIED)
    EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00000001177a7710
2. CoreUI: deallocating _CUIInternalLinkRendition 33643 /private/var/containers/Bundle/Application/3A1DCE31-2469-4701-9305-E18C10F85E3A/AppName.app/Assets.car
3. Crashed: TFMTRAFFICENGIN
   libsystem_kernel.dylib         0x1b3b110cc __pthread_kill + 8
   libsystem_pthread.dylib        0x1b3b88a88 pthread_kill + 300

**Comment by taras-bundziak** [comment]
Could you please share the mSDK version you used and steps on how to reproduce the crashes? Thanks.

**Comment by munish-techindustan** [comment]
@taras-bundziak, We are using here map SDK version 3.13 and tried to figure out the line of crash or code snippet where the crashes occur but these crashes seem to be **Memory Crashes** thus they are relevant to memory only. By debugging and running HereMaps Navigation for some hours, our app crashes due to insufficient memory. We found that **HereMaps** increases the memory uses continuously and results into crash and the crashes occurred only on the devices having memory around 200MB or even less than it.

**Comment by NazarKacharaba** [comment]
@munish-techindustan Could you provide:
1. route that you are navigating;
2. functionality in the HERE SDK that you use during navigation;
3. navigation settings that you use.

Thanks.

**Comment by munish-techindustan** [comment]
Thanks for the reply @NazarKacharaba App is crashing in turn by turn navigation and all crashes are due to RAM space or memory leaks. Can you please provide functionality or property of map to clear here map cache.

**Comment by NazarKacharaba** [comment]
Hi @munish-techindustan
>Can you please provide functionality or property of map to clear here map cache.

There is no such public functionality to clear RAM space in the HERE SDK.

We need more specifics to understand and reproduce this problem, could you provide data that we asked you before? Thanks.

**Comment by starand** [comment]
Closing ticket as no response.

**Comment by vivekkaushal99** [comment]
We are facing this issue for a long time now and is now affecting a lot of end users. We are currently using SDK v3.15. @NazarKacharaba details:
1. **"route that you are navigating"**: This is not a consistent issue, the same route might or might not reproduce this issue. Although all the routes are within US.
2. **"functionality in the HERE SDK that you use during navigation"**: Users are getting this issue during turn-by-turn navigation. Usually when users are navigating for prolonged hours, or starting and ending navigation multiple times (in some cases).
3. **"navigation settings that you use"**: We are using transport mode = truck and routing type = fastest. All the other things are default.
