### ISSUE TITLE
POI Search issue

### ISSUE THREAD

**Issue by moment101** [heremaps/here-ios-sdk-examples#156]
I searched POI by keywords, and sometimes I found the results are very strange.
For example, I want to find "Burbank Airport"

||search center  lat lon || :   34.1949582,-118.3540785

||keyword|| :

![search filters](https://user-images.githubusercontent.com/5095177/73821909-f20fb580-482f-11ea-837e-f237a9c43190.PNG)

Bu  -> found POI
Bur -> found POI
Burb -> error (code : 16)
Burba -> found POI

Is anyone know why "Burb" can't find POI ??

Thanks.

**Comment by starand** [comment]
Hi @moment101,
Which class do you use? Is it in Online or Offline mode? Which version of SDK do you use?

**Comment by starand** [comment]
Closing as no response.
