### ISSUE TITLE
Overlap text NMAMapLabeledMarker

### ISSUE THREAD

**Issue by VivekVithlani** [heremaps/here-ios-sdk-examples#157]
Hello,

I want to put **NMAMapLabeledMarker** like poi layer which is attached in the screenshot, Right now text overlap issue while **NMAMapLabeledMarker** added on the same coordinate (I am getting poi request for each map transition end and put NMAMapLabeledMarker on received coordinate).

**POI**
![POI](https://user-images.githubusercontent.com/8317975/74533090-c8a10900-4f56-11ea-9091-2fdc914458a9.PNG)

**Overlap text image 1**
![Overlap text 1](https://user-images.githubusercontent.com/8317975/74533140-e4a4aa80-4f56-11ea-8f23-34caeec0c8d1.PNG)

**Overlap text image 2**
![Overlap text 2](https://user-images.githubusercontent.com/8317975/74533114-d9ea1580-4f56-11ea-9467-717ea093f263.PNG)

**Overlap text image 3**
![Overlap text 3](https://user-images.githubusercontent.com/8317975/74533153-eb332200-4f56-11ea-8b87-525274863d23.PNG)

Thank you,
Vivek Vithalani.

**Comment by starand** [comment]
Hi @VivekVithlani,

Unfortunately this behavior is not implemented for labeled map markers.
But you can group them into clusters and handle tap on cluster. Clustering for labeled map markers is implemented in SDK 3.15 (release date is about 1st if Apr).

**Comment by VivekVithlani** [comment]
How could here map handle this kind of behavior in POI. If I want to implement like POI like here map, Please suggest me, Here map not used cluster right now.

**Comment by f4st** [comment]
Hi @VivekVithlani 

The HERE map embedded objects use complicated management that defines how to represent objects based on position, zoom level, map style, text, fonts, sizes, etc. 
This embedded functionality is not publicly available, please contact the sales representative for feature request.

Kind regards,
Mykola
