### ISSUE TITLE
Multiple NMARoutingOption

### ISSUE THREAD

**Issue by VivekVithlani** [heremaps/here-ios-sdk-examples#160]
How to set multiple ```NMARoutingOption``` like ```NMARoutingOptionAvoidBoatFerry``` &  ```NMARoutingOptionAvoidCarShuttleTrain```

is this correct code?
```
NMARoutingOption routingOption = NMARoutingOptionAvoidBoatFerry + NMARoutingOptionAvoidCarShuttleTrain;
[self createRouteWithType:NMARoutingTypeFastest RoutingOptions:routingOption withCounter:counter];
```

Thank you,
Vivek Vithalani

**Comment by starand** [comment]
@VivekVithlani 
You have to use bitwise OR instead - **"|"**:
`NMARoutingOption routingOption = NMARoutingOptionAvoidBoatFerry | NMARoutingOptionAvoidCarShuttleTrain;`
