### ISSUE TITLE
How to change color for some street?

### ISSUE THREAD

**Issue by hiteshborse12** [heremaps/here-ios-sdk-examples#163]
I have an iOS app with a map where the user can see roads of different colors with a specific meaning.

For example - Show some roads red which has a particular meaning and some roads green which has a different meaning etc. so that the user will see the map with color-coded roads.

All I have is the name of the road and the color which has to be assigned to the road from the API.

I am aware of Google Maps Platform Styling Wizard but that changes the color of all the roads in the map whereas I want to set the color to only specific roads and that also in different colors as required. Is it possible

**Comment by f4st** [comment]
Hello @hiteshborse12,

Thank you for interest in HERE SDK customisation. 
The Premium HERE SDK has functionality to customise MapView general representation by using `availableMapSchemes` and `mapScheme` properties of NMAMapView object ( e.g.: https://github.com/heremaps/here-ios-sdk-examples/blob/master/map-customization-ios ). Also HERE SDK has functionality to create MapObjects on MapView (e.g. https://github.com/heremaps/here-ios-sdk-examples/tree/master/map-objects-ios).
Set of the color for a street part can be achieved by next steps: 
1. Create a custom route that goes along some street( using `NMARoute` and `NMAGeoCoordinates`).
2. Create `NMAMapRoute` object using custom route created in step#1.
3. Set custom color for `NMAMapRoute` using its `color` property.
4. Add `NMAMapRoute` object on `NMAMapView` object.

BR, @f4st

**Comment by hiteshborse12** [comment]
Sorry, but I don't have Coordinates to draw a route. I just have a street name only. So we need to change the color of that road/street. Let me know is that possible to change the particular road/street color.

**Comment by hiteshborse12** [comment]
@f4st Only specific roads with different colors as required. Is it possible?

**Comment by f4st** [comment]
The route object with custom color can be implemented in application code by providing geocoordinates and using approach described in previous comment.

The described "custom color for specific street name" functionality is not available in SDK, please contact the sales representative for feature request.

BR, @f4st
