### ISSUE TITLE
Cannot install pod

### ISSUE THREAD

**Issue by hoangelec** [heremaps/here-ios-sdk-examples#17]
Today I've downloaded your sample projects, and tried running 'pod install', but I get this error: 
[!] Unable to find a specification for `HEREMaps`

Can you guys please check your pod project?

**Comment by abdullahselek** [comment]
Hi @hoangelec, can you try running `pod repo update` before running `pod install`?

**Comment by hoangelec** [comment]
I didn't try pod repo update, turned out that I need to run 'pod try HEREMaps' on the terminal before 'pod install'

**Comment by abdullahselek** [comment]
To update your pod local repository you can use `pod repo update` command. Ok then I am closing this issue.
