### ISSUE TITLE
"HERE SDK for iOS Evaluation Package expires on <date>" message

### ISSUE THREAD

**Issue by nhannguyen95** [heremaps/here-ios-sdk-examples#175]
Hi,

We're using Here Map Premium SKDs on iOS and having this warning message (despite the expiration date is in 2021)
<img width="207" alt="Screen Shot 2020-07-10 at 10 53 55" src="https://user-images.githubusercontent.com/9804766/87107895-e7a08e80-c29b-11ea-99d3-4023f39c3aec.png">. My question is how to make it disappeared? I want to now what triggers this message.

Thanks

**Comment by starand** [comment]
That happens because you use evaluation credentials. Contact your HERE representative in order to get proper credentials.
