### ISSUE TITLE
NMAClusterLayer theme not taking effect

### ISSUE THREAD

**Issue by fahlout** [heremaps/here-ios-sdk-examples#181]
The below code does not seem to work even though as far as I can tell it's exactly how it is outlined in the docs. My cluster marker still shows as a blue circle with a number instead of a green circle.

```swift
let clusterLayer = NMAClusterLayer()
let clusterTheme = NMAClusterTheme()
let clusterStyle = NMABasicClusterStyle(
    strokeColor: .green,
    fillColor: .green,
    fontColor: .white
)
let _ = clusterTheme.setStyle(clusterStyle, range: NSRange(2...))
clusterLayer.theme = clusterTheme
```

https://developer.here.com/documentation/ios-premium/3.16/dev_guide/topics/marker-clustering.html

**Comment by dashchak** [comment]
A problem is in range definition. 
From _setStyle_ [docs](https://developer.here.com/documentation/ios-premium/3.16/api_reference_jazzy/Classes/NMAClusterTheme.html#%2Fc:objc(cs)NMAClusterTheme(im)setStyle:forDensityRange:):
> Density range, minimum allowed start location is 2. The sum of the location and length of the range should not exceed NSIntegerMax value.

This is not correct. The sum should not exceed **INT32_MAX**. I will update docs in next release. Thanks!

As a workaround try to use:
`        let range = NSRange(location: 2, length: Int(INT32_MAX)-2)
`
In this case style will be applied to density from 2 to 2147483647 objects.

**Comment by fahlout** [comment]
Thanks. Your example seems to work. However, this is just poor API design. If I want to style all clusters the same there is really no need to specify a range. The range parameter should be optional and the default should be applying the style to all clusters. Furthermore, NSRange in Swift is less than ideal. I can use a more swift style range and convert it to an NSRange like this `NSRange(2..<Int32.max)`, but really I should be able to pass `2..<Int32.max` as the range without the NSRange cast.

To be clear `let _ = clusterTheme.setStyle(clusterStyle, range: NSRange(2..<Int32.max))` works and is a much cleaner way of defining the range than your example workaround.

**Comment by dashchak** [comment]
Agree, API is not complete. 
Starting from HERE SDK 3.17, new `setStyle:` method will be added to both iOS and Android SDKs. It will cover supported density from 2 to INT_MAX by default.

Still note, after calling `setStyle:` any further calls to `setStyle:range:` will return _false_ due to internal implementation of overlapped density ranges.
