### ISSUE TITLE
Distance to current maneuver

### ISSUE THREAD

**Issue by fahlout** [heremaps/here-ios-sdk-examples#182]
How do you get updates on the distance to the current and next maneuvers as the user is driving along a route while navigating? I want to be able to show the current distance and have it be current as the user drives. I tried KVO but that doesn't seem to work. I'm using the property `distanceToCurrentManeuver` on `NMANavigationManager`.

**Comment by dashchak** [comment]
Try to listen to position update notifications `NMAPositioningManagerDidUpdatePositionNotification` after `startTurnByTurnNavigation`. Following values should change while driving along a route:
- distanceToCurrentManeuver
- distanceToNextManeuver
- distanceToDestination
- distanceFromStart
- remainingDistance(toSubleg:)
- remainingDistance(toRouteElement:positionOnElement:)

**Comment by fahlout** [comment]
Thanks that helped.
