### ISSUE TITLE
Navigation Pause and Resume not work iOS

### ISSUE THREAD

**Issue by arunmt024** [heremaps/here-ios-sdk-examples#198]
**Describe the bug**
When my navigation process is ongoing at that time I need to pause navigation and resume navigation. I use the following for pause navigation

For Paused : [NMANavigationManager sharedNavigationManager].paused = YES;

but when I use Paused my position update is not stop and my visible marker position still changing. let me know the proper way to pause the visible marker and pause position update.

**Comment by arunmt024** [comment]
Any Suggestion on that ?

**Comment by dashchak** [comment]
You can use stopPositioning/startPositioning of NMAPositioningManager. 
Or `mapView.positionIndicator.visible = true/false`. 

Note, `paused` is also used by SDK when app goes in background during active navigation.

**Comment by arunmt024** [comment]
mapView.positionIndicator.visible = true at that time its hide but when I resume navigation again. its goes to origin to destination with fly

**Comment by dashchak** [comment]
Correct, it can not be changed via public API.

**Comment by arunmt024** [comment]
so how to pause indicator?

**Comment by dashchak** [comment]
Before enabling position indicator you can start positioning. So position should be updated to the current one first and then shown on the map without jumping to previous.
As a workaround to prevent fly animation, you can explicitly call 
`mapView.set(geoCenter: myCurrentPosition, animation: .none)`
right before resuming the navigation.
