### ISSUE TITLE
How to Visible marker image set ?

### ISSUE THREAD

**Issue by arunmt024** [heremaps/here-ios-sdk-examples#201]
- I want to change the visible marker image. can you please give an idea about that

**Comment by dashchak** [comment]
You can create NMAImage by using `initWithUIImage` and then assign it to NMAMapMarker `icon` property.
Please kindly read a [Dev Guide](https://developer.here.com/documentation/ios-premium/3.18/dev_guide/topics/map-objects-and-interaction.html) and [SDK documentation](https://developer.here.com/documentation/ios-premium/3.18/api_reference_jazzy/index.html) before creating issue for each of your question.
