### ISSUE TITLE
When we are not in map screen voice instruction come but not call delegate method hasCurrentManeuver [issue on foreground mode ]

### ISSUE THREAD

**Issue by arunmt024** [heremaps/here-ios-sdk-examples#202]
navigationManager:(NMANavigationManager*)navigationManager
       hasCurrentManeuver:(NMAManeuver*)maneuver
             nextManeuver:(NMAManeuver*)nextManeuver

**Comment by dashchak** [comment]
Sorry I don't understand the question. Could you please fill in all details specified in new issue template

**Comment by arunmt024** [comment]
on foreground mode when we are not present in the map screen at that time following delegate method not call but voice instruction I got.

- (void)navigationManager:(NMANavigationManager*)navigationManager
       hasCurrentManeuver:(NMAManeuver*)maneuver
             nextManeuver:(NMAManeuver*)nextManeuver

**Comment by dashchak** [comment]
If you use Swift, try this:

```
 // Signifies that there is new instruction information available
 func navigationManager(_ navigationManager: NMANavigationManager,
                        didUpdateManeuvers currentManeuver: NMAManeuver?,
                        _ nextManeuver: NMAManeuver?) {
     showMessage("New maneuver is available")
 }
```
Please provide sample code where you can reproduce it. You may modify [ours.](https://github.com/heremaps/here-ios-sdk-examples/tree/master/turn-by-turn-navigation-ios-swift)

**Comment by arunmt024** [comment]
- (void)navigationManager:(nonnull NMANavigationManager*)navigationManager
       hasCurrentManeuver:(nullable NMAManeuver *)currentManeuver
             nextManeuver:(nullable NMAManeuver *)nextManeuver
NS_SWIFT_NAME(navigationManager(_:didUpdateManeuvers:_:));



@dashchak  you give me the same method name which I post :). I am using objective c.

**Comment by dashchak** [comment]
Please provide sample app where you can reproduce it.

**Comment by dashchak** [comment]
Closing as not response received. Please create new ticket if issue is reproduced on the latest v3.19.2
