### ISSUE TITLE
On Marker click i want to show bubble info

### ISSUE THREAD

**Issue by arunmt024** [heremaps/here-ios-sdk-examples#203]
How to show Bubble info on iOS on click of a marker

**Comment by dashchak** [comment]
Try [NMAMapOverlay Class](https://developer.here.com/documentation/ios-premium/3.18/dev_guide/topics/map-objects-and-interaction.html). 
You can init it with custom UIView as well as with geo coordinates and anchorOffset.

Here SDK does not support dedicated marker bubbles.
