### ISSUE TITLE
How to get Total travel in Highways/Local/Interstate

### ISSUE THREAD

**Issue by arunmt024** [heremaps/here-ios-sdk-examples#204]
how to get Total travel in Highways/Local/Interstate (time and Distance)

**Comment by dashchak** [comment]
Unfortunately mSDK does not have such APIs.

To work around somehow a traveled distance calculation logic, following API can be used: 
`distance(fromRouteElement:fromPosition:toRouteElement:toPosition:)`

Note, created route contains array of `routeElements`. Route element usually has corresponding `roadElement`. By using its `NMARoadElementAttributeHighway` it is possible to identify is it highway or other kind of road element. Also, check out `currentRoadElement` of `NMAPositioningManager`.
