### ISSUE TITLE
Street-level Imagery swift 3 documentation  

### ISSUE THREAD

**Issue by sundus555** [heremaps/here-ios-sdk-examples#21]
i need a documentation for the HERE map SDk using swift 3 
All the examples written with objectiv-c iam trying to build  a HERE Map Street-level Imagery
project using swift 3 >>>please contact me ASP

**Comment by SirBif** [comment]
Is there any example available we can share @AmbroseLi ?

**Comment by AmbroseLi** [comment]
Swift samples are in our backlog but haven't been put into a sprint yet.  I'll see if we can get this particular one scheduled.

**Comment by dashchak** [comment]
SLI is not supported anymore
