### ISSUE TITLE
Overlay move with turn by turn navigation issue 

### ISSUE THREAD

**Issue by vishalparmar22091989** [heremaps/here-ios-sdk-examples#219]
UIView *annotView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 50, 20)];
 annotView.backgroundColor = [UIColor redColor];
 NMAMapOverlay *overlay = [[NMAMapOverlay alloc] initWithSubview:annotView]; overlay.coordinates = //your location's NMAGeoCoordinates [self.mapView addMapOverlay:overlay];

**Comment by dashchak** [comment]
Hi @vishalparmar22091989 
Please check altitude of overlay's coordinate is 0.
If it is not the root cause, please specify more details. i.e. capture video

**Comment by vishalparmar22091989** [comment]
@dashchak  Thank you for the quick response. following video link and I am using like following

Issue video link : https://drive.google.com/file/d/1G6BA4_rzN22RPW-SPumhcHqutjSsJAiR/view?usp=sharing

     ```
NMAGeoCoordinates* hereBurnaby =
          [[NMAGeoCoordinates alloc] initWithLatitude:[[markerObj objectForKey:@"latitude"] doubleValue] longitude:[[markerObj objectForKey:@"longitude"] doubleValue] **altitude:0]**;
      
      UILabel *label = [[UILabel alloc] initWithFrame:CGRectZero];
      label.textColor = [UIColor whiteColor];
      label.text = markerObj[@"title"];
      label.textAlignment = NSTextAlignmentCenter;
      label.backgroundColor = [UIColor grayColor];
      label.layer.borderWidth = 2;
      label.numberOfLines=4;
      label.frame = CGRectMake(0, 0, 220, 60);
      [label setFont:[UIFont systemFontOfSize:12]];

      NMAMapOverlay *overlay = [NMAMapOverlay mapOverlayWithSubview:label geoCoordinates:hereBurnaby];
      [arrOverlay addObject:overlay];
      [mapView addMapOverlay:overlay];
```

**Comment by dashchak** [comment]
Our QA team can not reproduce the issue on the latest v3.18.5.
Could you please specify iOS, mSDK versions?
Is it reproduced on all locations on the map after some gestures?

Also please make sure coordinates of your marker are not dynamically changed when navigation starts. Otherwise it will also change coordinates of mapOverlay and make it move together with marker.

**Comment by vishalparmar22091989** [comment]
same issue with latest SDK from my side
