### ISSUE TITLE
Crazy archived .ipa file size 

### ISSUE THREAD

**Issue by hoangelec** [heremaps/here-ios-sdk-examples#22]
Hello, 

I'm having a problem with the .ipa file size. Previously I was using older version (v3.1, which I manually added to my project) and everything went fine, the archived .ipa file was around 60MB in size. 

However just lately I've updated the framework to the latest version via Pod, and to my astonishment, the archived .ipa file went up to 280MB in size, which is absolutely not an reasonable number. I cannot submit my app in this condition. 

Can anyone please check this? Or at least suggest a solution?

**Comment by SirBif** [comment]
Hi @AmbroseLi , do you know what happened here? I took a quick look, and the size of NMAKit went from 131 MB in version 3.3 to 549 MB in version 3.5. This would explain the increase in the ipa size

**Comment by hoangelec** [comment]
For those who's suffering the same issue, I managed to reduce the size by removing HEREMaps from my podfile, then I downloaded the framework from developer.here.com and add it to my project manually. The problem just magically went away

**Comment by AmbroseLi** [comment]
Hi @hoangelec , after you built your app, did you Export it to the target (e.g., Development, Enterprise, App Store, etc.)?  The size of the app is bloated when built using the podspec but after the export, then it goes back to its smaller size.

**Comment by hoangelec** [comment]
Yes I did export it, it was the binary .ipa file for Appstore submission.

**Comment by hoangelec** [comment]
Any news yet?

**Comment by AmbroseLi** [comment]
Hi @hoangelec , sorry for the delay; we logged a ticket over here and it has been assigned to a developer to investigate.

**Comment by AmbroseLi** [comment]
We uploaded a number of combinations; manual embedding of NMAKit built with and without bitcode, NMAKit installed via CocoaPods (built with bitcode).  Observed that the app (which uses map, guidance, ODML, traffic and routing services) download and install size on end user devices are the same in all cases.  What steps are you using to get your numbers?  We get the app store sizing info this way:

1. Archive app in xcode
2. Upload archive to app store
3. Wait for App store to finish processing archive and view app details in iTunesConnect
4. Click on "App Store File Sizes"

**Comment by hoangelec** [comment]
Sorry for the late response. I've checked and found that the size of my build after uploaded to Appstore is around 120MB, it's significantly less than 300MB of the original archived file by XCode.

**Comment by lakersr8ers** [comment]
Any updated recommendations here? The NMAKit.framework is 648MB from what i can tell (and this is the case even after stripping simulator architectures).
