### ISSUE TITLE
HEREMaps doesn't appear in Pod's Targets

### ISSUE THREAD

**Issue by hoangelec** [heremaps/here-ios-sdk-examples#23]
Hello HERE developers, 
I'm having a problem with NMAKit while using pod for installation. In my podfile I've added _pod 'HEREMaps'_ , but after running _pod install_ my project won't compile, and I don't see HEREMaps (or NMAKit) in the list of pod's generated targets : https://monosnap.com/file/rGBzgiM809dn33JD1aq0ta37V0Si1n

Eventually I need to manually add NMAKit.framework to my main project in order for my project to compile, however because NMAKit is not in the pod's generated target, I cannot disable BIT_CODE and submit the archived binary to appstore. 

I'm a premium user and this really annoys me. Please investigate and fix this.

**Comment by JH-YVR** [comment]
@hoangelec can you  confirm if this issue still exists. We have not been able to reproduce the issue. Thanks.

**Comment by hoangelec** [comment]
Due to this issue https://github.com/heremaps/here-ios-sdk-examples/issues/22 I had to switch to manual integration instead of using pod.
