### ISSUE TITLE
Any swift 4 support ?

### ISSUE THREAD

**Issue by joyalserrao** [heremaps/here-ios-sdk-examples#32]
All example on Obj-C , Looking for  swift updates

**Comment by AmbroseLi** [comment]
Hi.  We have the redone the set of Obj-C samples in Swift internally already.  Just a bit more review over here and we'll be putting them up.

**Comment by joyalserrao** [comment]
I done turn by turn in swift Please check my repo onces: https://github.com/joyalserrao/HEREmaps-TurnByTurn-Swift-4-Exmp

**Comment by Xgamefactory** [comment]
objc is more mature and good decision for such projects. swift is for a student to having fun )
mapbox ios sdk is built with swift teenagers and has tons of issues we are switched to heremaps sdk because it is built by professionals with professional language )
