### ISSUE TITLE
create NMAMapView without storyboard 

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-ios-sdk-examples#36]
Hi,
Is it possible to create NMAMapView without using storyboard.
We are currenty developing ios static library with here maps

**Comment by JH-YVR** [comment]
Does the following taken from the User Guide help?

The first step to integrate a map into an application is to insert a NMAMapView to your view controller's
.xib file or the storyboard of the application using the Interface Builder. Alternatively, you can also add
NMAMapView to your view controller programmatically as follows:

```
- (void)viewDidLoad
{
mapView = [[NMAMapView alloc] initWithFrame:self.view.frame];
[self.view addSubview:mapView];
}
```

**Comment by Xgamefactory** [comment]
thanks but where can we set app credentials for static library project ?

```
- (BOOL)application:(UIApplication *)application
didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [NMAApplicationContext setAppId:@"{YOUR_APP_ID}" 
  appCode:@"{YOUR_APP_CODE}" 
  licenseKey:@"{YOUR_LICENSE_KEY}"];

  return YES;
}
```
