### ISSUE TITLE
signing error: Bundle identifier not specified

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-ios-sdk-examples#37]
Hi,
We are getting **"Signing error: Bundle identifier not specified"** error during generating ipa.

looks like your framework file not unsigned unlike other third party framework files we have used before.that is why encountering such error.
Could you provide unsigned .framework file ?

**Comment by RN-202** [comment]
As customer using framework will be resigning their app with their own identity (see https://stackoverflow.com/questions/30963294/creating-ios-osx-frameworks-is-it-necessary-to-codesign-them-before-distributin), what is your use case that you will need the .framework to be unsigned?

**Comment by Xgamefactory** [comment]
we have implemented map box.framework successfully but with nmakit.framework
getting error
`Signing Error: Bundle identifier not specified.`
could not figured out the reason

**Comment by RN-202** [comment]
Under General settings of your Xcode project (selecting your app as the target), make sure the "Bundle Identifier" is set and is same as what you have registered on developer.here.com. Please refer to https://developer.here.com/documentation/ios-premium/topics/app-create-simple.html for more details.
