### ISSUE TITLE
How to display textual navigation instructions on screen.

### ISSUE THREAD

**Issue by Simeryn** [heremaps/here-ios-sdk-examples#49]
I am using **HERE** maps for navigation functionality in my project. Navigation is working fine, but now I want to **display the textual directions** on the screen.

I could find the list of `ENums` that return integer values for the turns taken

![list of enums](https://user-images.githubusercontent.com/23739970/41461992-01345ce6-70af-11e8-9ca2-bdcf491e2152.png)

but am clueless on how to use this data to represent the text for turns on the screen as they return just integer numbers, not a text.

For example:

If left turn is taken it gives me **9** instead of "**Take a quite left**".

This solution is available in android but I don't know to how to work it out in iOS.

Any help is appreciated, thank you.

**Comment by starand** [comment]
Hi @Simeryn 
Which method/API do you use on Android to convert Turn enum to String?
iOS SDK does not have public API to convert the enum to text messages. But you can create your own string array.

**Comment by Simeryn** [comment]
@starand Yea I did the same. I had to type my own strings thank you for replying. Closing this issue.
