### ISSUE TITLE
getMapPackageAtGeoCoordinates does not call the delegate method

### ISSUE THREAD

**Issue by orri14** [heremaps/here-ios-sdk-examples#50]
getMapPackageAtGeoCoordinates returns true, but does not call mapLoader:didGetMapPackage:atGeoCoordinates:withResult.

SDK Version: 3.7.0.118

**Comment by tlushney** [comment]
Thanks @orri14 to point it. getMapPackageAtGeoCoordinates is asynchronous call and returns true as soon as request is sent to the server. The issue can happens only when server returns the error.
So it should never happen during regular scenario. We will plan to fix the error - but for now we recommend to treat the situation as comunication error with the server.

**Comment by dashchak** [comment]
Issues will be fixed in 3.10 SDK. 

mapLoader:didGetMapPackage:atGeoCoordinates:withResult: should return nil map package with NMAMapLoaderResultSearchFailed result in case of connection issues.
