### ISSUE TITLE
Turn-by-turn-navigation doesn't fire navigationManagerDidFindPosition delegate method

### ISSUE THREAD

**Issue by oli06** [heremaps/here-ios-sdk-examples#68]
Hi, 

when running the GuidanceApp / Turn-by-turn-navigation project, the navigationManagerDidFindPosition function is never called. Neither using the simulation mode nor using "real navigation" with a custom .gpx-file or apple's location examples. 

When does the NavigationManager delegate normally calls this method?

Thanks for your help.

**Comment by simonoff** [comment]
@oli06 how you fixed it?
