### ISSUE TITLE
Autozoom issue during turn by turn

### ISSUE THREAD

**Issue by ravinford** [heremaps/here-ios-sdk-examples#77]
I have a recenter button in my turn by turn navigation view. 

The logic behind the recenter button is as follows: 

- When I press recenter it sets `mapTrackingEnabled` and `mapTrackingAutoZoomEnabled` to true. 
- When the `mapViewDidBeginMovement` function is called I set `mapTrackingEnabled` and `mapTrackingAutoZoomEnabled` to false.

It only seems to happen when the user's position is in the top left or top right of the map.

Here is a gif showing what happens:
![ezgif-6-068fca3a68d6](https://user-images.githubusercontent.com/19913646/48234917-7eeb6b00-e370-11e8-8e7b-33bc00851b9a.gif)

**Comment by ArtisOracle** [comment]
We are also experiencing this issue. This seems to happen most noticeably when the user recenters the map in the top 1/5th of the map view bounds.

![heremapsbug](https://user-images.githubusercontent.com/1455368/49761202-59fe5680-fc94-11e8-9661-b9d42b5f421a.gif)

**Comment by ArtisOracle** [comment]
We ended up mitigating this behavior by re-centering the map with no animation (`mapView` is an `NMAMapView` instance):

`mapView.set(geoCenter: NMAGeoCoordinates(latitude: coordCurrent.0, longitude: coordCurrent.1), animation: .none)`

**Comment by VivekVithlani** [comment]
Hello,

When you enable **`mapTrackingEnabled`** then remove **`mapView.set(geoCenter: NMAGeoCoordinates(latitude: coordCurrent.0, longitude: coordCurrent.1), animation: .none)`** code.
