### ISSUE TITLE
NMAKit crashes on ios (SIGSEGV)

### ISSUE THREAD

**Issue by Xgamefactory** [heremaps/here-ios-sdk-examples#80]
Unfortunately we do not have heremaps ios sdk dsym file to resymbolicate and udnerstand the reason.
```
Exception Type:  SIGSEGV
Exception Codes: SEGV_ACCERR at 0x0
Crashed Thread:  26

Thread 0:
0   NMAKit                              0x00000001037688e8 0x102934000 + 14895336
1   NMAKit                              0x00000001030eeb84 0x102934000 + 8104836
2   NMAKit                              0x00000001030ee938 0x102934000 + 8104248
3   NMAKit                              0x0000000102fb001c 0x102934000 + 6799388
4   NMAKit                              0x00000001037fcfc0 0x102934000 + 15503296
```

**Comment by f4st** [comment]
Hi @Xgamefactory , 

Thank you for reporting the issue. We need more details from your .crash file to start work on it. 
In opened issue you have added the "Thread 0" call stack while "Thread 26" crashed.
Could you please provide more information regarding the crash? 

BR,
@f4st

**Comment by Xgamefactory** [comment]
sorry for late response we will response asap.
