### ISSUE TITLE
License key?

### ISSUE THREAD

**Issue by petec029** [heremaps/here-ios-sdk-examples#87]
The instructions say to update the appdelegate with the license key from my credentials.  I see an app id and app code but nothing that says license key.  Where do I get the license key to use in the sample ios apps?

**Comment by f4st** [comment]
Hi @petec029,

Thank you for asking this question. 
The license key is required for Premium SDK usage, and is not available in Starter SDK. All these samples (https://github.com/heremaps/here-ios-sdk-examples/) are using Premium SDK.
You can generate the license key for sample application by registering application data in your HERE account.

The sample code contains the hint:
> // To obtain the application credentials, please register at https://developer.here.com/develop/mobile-sdks

Small guide how to get License key for Premium SDK application:
1. Open link: [https://developer.here.com/develop/mobile-sdks](https://developer.here.com/develop/mobile-sdks)
2. Register HERE account:
![here_register_for_license_keys](https://user-images.githubusercontent.com/3294690/50824658-d80b5700-133f-11e9-84d8-9953de0b0313.png)
3. Login into HERE account and select project list:
 ![here_account_projects](https://user-images.githubusercontent.com/3294690/50826626-d1cba980-1344-11e9-8a04-d158e3b8edbf.png)
4. In appeared section create a plan for new project (you can skip this step if you already registered  the plan):
![select_here_plan_for_project](https://user-images.githubusercontent.com/3294690/50826792-56b6c300-1345-11e9-876d-8b256150e327.png)
5. Select already created project plan and press "Generate App Id and App Code" button (for Premium SDK): 
![here_generate_appcode_and_license_key](https://user-images.githubusercontent.com/3294690/50827164-6682d700-1346-11e9-99e0-b8cb6ce0a0c5.png)
6. In appeared view enter application Bundle ID (e.g: For geocoder-and-reverse-geocoder-ios sample Bundle ID is nma.iOSHereSDKSamples.GeocoderRevGeocoder) and press "Generate" button
![here_generate_license_key_for_application](https://user-images.githubusercontent.com/3294690/50827307-c8dbd780-1346-11e9-9e4e-68349c39b582.png)

Then you can copy generated App ID, App Code and License Key into your application AppDelegate file and run the application.

BR, 
@f4st

**Comment by petec029** [comment]
Thanks for the reply.  I already did that and there is no license key on the screen.  I got a call from Scott at Korem today and he said there were changes going on back in early Nov when I did this and to delete my project and try it again.  Will try that when I get a chance and let you know how I make out.
