### ISSUE TITLE
Implementing NMAMapGestureDelegate  make the map unusably slow 

### ISSUE THREAD

**Issue by boudellaredouane** [heremaps/here-ios-sdk-examples#91]
If i implemente any of the NMAMAPGestureDelegate protocol's methods regarding the pan gestures, the map becomes suddenly painfully slow, be it on the simulator or an actual test device.

I am pulling the sdk through cocoapods for a swift projet

Is this a newly introduced bug ? can i roll back to a previous version of the sdk ?

these are the ones i tested : 

```
- (void)mapView:(nonnull NMAMapView *)mapView didReceivePan:(CGPoint)translation atLocation:(CGPoint)location NS_SWIFT_NAME(mapView(_:didReceivePan:at:));

- (void)mapView:(nonnull NMAMapView *)mapView didReceiveTwoFingerPan:(CGPoint)translation atLocation:(CGPoint)location NS_SWIFT_NAME(mapView(_:didReceiveTwoFingerPan:at:));
```

**ENV:**
issue encoutered on both Xcode 9.2 / Xcode 10.0
Cocoapods first pulled the 3.6 version and then i tested with 3.5 thinking it s a new introduced bug, but the issue remained

**Comment by boudellaredouane** [comment]
Is there any news on this ? nothing :(

**Comment by f4st** [comment]
Hi @boudellaredouane,

Have you tried [map-gestures-ios](https://github.com/heremaps/here-ios-sdk-examples/tree/master/map-gestures-ios) sample from current repository?

Kind regards,
@f4st

**Comment by boudellaredouane** [comment]
@f4st 
Had some issues earlier with cloning the repos, now i ve just tried it, it worked nicely.

I read through the code and then through the Protocol's .h file and found this

> [mapView.defaultGestureHandler mapView:mapView didReceiveTapAtLocation:location];  // optional

I added this call to the delegate method implementation and everything fell into place.

Why is it marked as optional ?  coz as per my experience this is not optional.

The docs may need a check.

Closing this issue.

**Comment by f4st** [comment]
> I added this call to the delegate method implementation and everything fell into place.
> Why is it marked as optional ? coz as per my experience this is not optional.
> The docs may need a check.
Thank you for response.  'Optional' comment will be removed in future(3.11) release.
