### ISSUE TITLE
MapOverlay doesn't in the same place on the map with marker

### ISSUE THREAD

**Issue by guoliang1206** [heremaps/here-ios-sdk-examples#92]
I have create the markers and overlays with same coordinates. but they didn't at same place 
![ba9040df-9a91-4788-9930-e84d5cbf3af5](https://user-images.githubusercontent.com/12846676/53384105-bb40e680-39b4-11e9-99b3-349f8a718192.png)

And when I drag the map, overlays can't moved correctly as markers. 

enviroment : iOS 12.1

**Comment by guoliang1206** [comment]
I have compared with google maps, the marker's place is right, but all overlay's places are wrong.

**Comment by dashchak** [comment]
Could you please specify SDK version and share your code snippet?

**Comment by guoliang1206** [comment]
@dashchak  
Hi, there has a link
https://stackoverflow.com/questions/54878938/ios-sdk-nmamapoverlay-didnt-displayed-at-right-place

**Comment by dashchak** [comment]
Issue will be fixed in 3.11.

As a workaround try to init **mapOverlay** with 0 altitude coordinate.
```
NMAGeoCoordinates *coords = [[NMAGeoCoordinates alloc] initWithLatitude:_coordinate.latitude longitude:_coordinate.longitude altitude:0]; 
self.overlayView = [[NMAMapOverlay alloc] initWithSubview:label geoCoordinates: coords];
```

**Comment by guoliang1206** [comment]
@dashchak  thank you !

**Comment by abozzelli** [comment]
setting altitude to 0 is not working if the map is assigned to a navigation manager. Is there any other workaround?
