### ISSUE TITLE
Unable to set marker on map

### ISSUE THREAD

**Issue by illabo** [heremaps/here-ios-sdk-examples#95]
Hello there!
Checked docs and examples, tried setting image as literal, accessing by asset name, setting on NMAMapMarker init, setting it as value (`marker.icon = UIImage(named: "marker.png")`). Nothing helped.
I can see the marker as an object in debugger and `mapView.add(marker)` returns `true`, map scrolls to that place when I pass the same point to `set()` method of NMAMapView, but I can't see actual marker on a map. 
Can't say whether it is my mistake or something's really broken in SDK?
```
let marker = NMAMapMarker(geoCoordinates: point, image: UIImage(named: "marker.png"))
mapView.add(marker)
let zoom = zoomLevel ?? mapView.zoomLevel
mapView.set(geoCenter: point, zoomLevel: zoom, animation: .linear)
```
Swift 5, iOS 12.2, project's build target iOS 10.0

**Comment by f4st** [comment]
Hello @illabo ,

Thank you for asking a question. 
We were not able to compile your code without errors, so we updated it: 
```
let marker = NMAMapMarker(geoCoordinates: point, image: UIImage(named: "marker.png")!)
mapView.add(mapObject:marker!)
let zoom = zoomLevel ?? mapView.zoomLevel
mapView.set(geoCenter: point, zoomLevel: zoom, animation: .linear)
```
The code above works with your environment settings `Swift 5, iOS 12.2, project's build target iOS 10.0`
Please ensure that image "marker.png" exists in your project. 
Also you can try sample https://github.com/heremaps/here-ios-sdk-examples/tree/master/map-objects-ios-swift which has `createMapMarker` example.

Kind regards,
@f4st

**Comment by illabo** [comment]
Thank you, for the answer @f4st

I'm using HEREMapsStarter (3.11.0) and `mapView.add(mapObject:marker!)` isn't seem as valid method in this version of sdk. The valid method signature is `func add(_ object: NMAMapObject) -> Bool`. I assume it is the one of starter and premium versions differences. 

> Please ensure that image "marker.png" exists in your project.

Yes the image is definitely is present in my project. 
Actually I'm able to set the marker image when it is retrieved  by url from NMAPlace object ` place.categories?.first?.iconUrl`. And the following icon could be set without a problem too: https://github.com/heremaps/here-ios-sdk-examples/blob/master/search-ios-swift/marker.png. 
But it shows nothing with some images e.g. this one https://icons8.com/icon/59830/marker and some other pics.

**Comment by f4st** [comment]
@illabo, thank you for providing more details.
The heremaps/here-ios-sdk-examples are for iOS Premium SDK, so I decided that you were using Premium iOS SDK, not Starter SDK.

Regarding Starter SDK usage - I've modified https://github.com/heremaps/here-ios-sdk-examples/tree/master/map-objects-ios-swift locally with your code and was able to draw a marker that you mentioned: 

> But it shows nothing with some images e.g. this one https://icons8.com/icon/59830/marker and some other pics.

The marker is drawn as expected:
![StarterSDK_marker_with_user_image](https://user-images.githubusercontent.com/3294690/56602240-acb62a80-6605-11e9-8a51-031b51a3c49c.png)


Please ensure that mapView is initialized before you adding an object and marker image exists.
If you able to reproduce the issue - please provide us with sample for the root cause investigation.

Kind regards,
@f4st

**Comment by illabo** [comment]
@f4st thank you for reply.
Sorry not mentioning that I'm using starter SDK right in the first message. To say truly I didn't expect that the difference is any critical.
Regarding the case. Nope I am still unable to set different marker image rather the one from this repo. 
![IMG_7505](https://user-images.githubusercontent.com/6376785/56646297-a46ff500-66c2-11e9-8802-d37c6ab14bda.PNG)
Whenever I try different images nothing appears on map, but still I definitely can see the marker object in debugger. (It is set on the screenshot below)
![IMG_7503](https://user-images.githubusercontent.com/6376785/56646432-e6993680-66c2-11e9-91d6-09612d7d20d6.PNG)
Here is the code of the method to set the marker:
```
        func setPin(at point: NMAGeoCoordinates, center: Bool = false, zoomLevel: Float? = nil, iconURL: String? = nil){
            mapView.remove(objects: displayedObjects)
            displayedObjects.removeAll()
            suggestions.removeAll()
            var icon = #imageLiteral(resourceName: "MarkerMM") // works with only default image, shows nothing with custom images
            let marker = NMAMapMarker()
            marker.coordinates = point
            marker.icon = icon
            marker.zIndex = 100
//            able to retrieve and set image from NMAPlace: place.categories?.first?.iconUrl
//            if let iconURL = iconURL, let url = URL(string: iconURL) {
//                URLSession.shared.dataTask(with: url) { (data: Data?, response: URLResponse?, error: Error?) in
//                    guard let data = data, let image = UIImage(data: data), error == nil else {
//                        print("Failed downloading icon with error:", error ?? "unknown error")
//                        return
//                    }
//                    marker.icon = image
//                }.resume()
//            }
            if marker.icon != nil {
                mapView.add(marker)
                displayedObjects.append(marker)
                if center {
                    let zoom = zoomLevel ?? mapView.zoomLevel
                    mapView.set(geoCenter: point, zoomLevel: zoom, animation: .linear)
                }
            }
            
        }
```
It is the part of a ViewController which is inited with mapView `private var mapView = NMAMapView()`. 
The pin could only be set after `viewDidLoad()` where the search field and gestures delegates are set up. Only taps, CLLocationManagerDelegate or UITextFieldDelegate methods could reach `setPin`.
Again, everything is smooth with the images from this repo as the marker icons. Feel like I'm missing something obvious. 

> If you able to reproduce the issue - please provide us with sample for the root cause investigation.

Do you mean a sample app or a class that utilizes the mapView?
Thanks.

**Comment by f4st** [comment]
> > If you able to reproduce the issue - please provide us with sample for the root cause investigation.
> 
> Do you mean a sample app or a class that utilizes the mapView?

@illabo , small sample app that can be used to reproduces your issue. It should contain minimum code that needed for issue. Please create this issue sample in your repository and share a link here.

Kind regards,
@f4st

**Comment by starand** [comment]
@illabo, is there any updates? Did you solve your issue? If there is no response we will close the ticket. Thank you!

**Comment by illabo** [comment]
@starand, nope, I haven't solve the issue. Will provide sample app later, so please keep the ticket open for a while yet.

**Comment by illabo** [comment]
@f4st, @starand thanks for the wait, was busy recently. Here's [the demo project](https://github.com/illabo/here-marker-demo). Buttons on top of the map are setting pins at random locations, first two pins aren't visible on the map (on my device and in simulator), last one (found in this repo) is visible as expected.

**Comment by f4st** [comment]
@illabo thank you for demo project, it helped us to determine the reason.
The reason is in **monochrome** color space model. 

The Starter SDK doesn't support the monochrome color space model, it works with the RGB color space model.

Your demo project issue can be solved by using images with RGB color space model.
The **recommended way** to solve it is manually convert images to RGB and replace them in assets.
The alternative way is to use [runtime image adjustment](https://github.com/f4st/here-marker-demo/commit/1ebbb209922a9041dfcd77236fa215c3c5ffee6b), but it has impact on application performance and memory.

Kind regards,
@f4st

**Comment by illabo** [comment]
@f4st, thanks a lot for cooperation! Don't think I'd be able to find the cause of this issue by myself.

Thanks again for your time and effort solving the issue.
