### ISSUE TITLE
How to show downloaded region in NMAMapView?

### ISSUE THREAD

**Issue by imanuelpardosi** [heremaps/here-ios-sdk-examples#99]
Hi there!
I downloaded and run map-downloader-ios-swift project and it worked well. After finished download 1 region, how do we show that region in mapview without an internet connection? And is it possible to add routes in that downloaded region in offline mode?

**Comment by f4st** [comment]
Hello @imanuelpardosi 

Thank you for asking a question. 
There are 2 approaches of Map Data download which are used in Premium SDK:
1) Passive approach
2) Active approach

The passive (also known as downloaded on-demand) is executed implicitly for developer. When user scrolls the map to previously not visible region - the mapView downloads the data for representation and caches it. This approach stores minimum data and will not allow to use routing in offline. 

The active approach has two alternatives:
A) Map Packages
B) Bounding Box or Route 

The Premium SDK supports offline mode to build a route, but map packages should be previously downloaded. After package was downloaded you can show any its region by setting mapView geoCenter. E.g:
```
NMAGeoCoordinates *geoCoordCenter = [[NMAGeoCoordinates alloc]
 initWithLatitude:49.260327 longitude:-123.115025];
[self.mapView setGeoCenter:geoCoordCenter withAnimation:NMAMapAnimationNone];
```

Kind regards,
@f4st

**Comment by imanuelpardosi** [comment]
Hi @f4st, thank you so much for the great explanation! Will try your solution.
My question, do you have example project of Bounding Box or Route, cause I didn't see in this repository. Thank you.

**Comment by f4st** [comment]
Hi @imanuelpardosi,

The NMAMapDataPrefetcher is used for Bounding Box or Route map data download. Currently we don't have a example project, but these methods code examples are described in [documentation](http://documentation.developer.here.com/pdf/maps_ios_nlp_hybrid_plus/3.11/HERE%20iOS%20SDK%20Premium%20Edition%20v3.11%20Developer's%20Guide.pdf) (section "Map Download by Specifying a Bounding Box or Route").
Note that these options will have limits in size (depending on cache), while NMAMapLoader wouldn't.

Kind regards,
@f4st

**Comment by imanuelpardosi** [comment]
Hi @f4st, thank you, I already read the documentation. 

I have another question about Map Packages, after I downloaded one regional, is it possible to use NMANavigationManager in offline mode? I wanna provide voice and visual instructions in offline mode.

Thanks in advance.

**Comment by f4st** [comment]
Hi @imanuelpardosi,

> I have another question about Map Packages, after I downloaded one regional, is it possible to use NMANavigationManager in offline mode? I wanna provide voice and visual instructions in offline mode.

The HERE SDK Premium edition supports offline usage. After map packages for required region are downloaded the route calculation and navigation guidance (voice and visual instructions) will be available in offline mode.

NOTE that feature list depends from your license key. In case the trial period of feature has expired please contact the sales representative.

Kind regards,
@f4st

**Comment by imanuelpardosi** [comment]
Hi @f4st, thank you so much! :)

**Comment by JayeshMardiya** [comment]
@imanuelpardosi How did you download map using bounding box?

**Comment by dashchak** [comment]
@JayeshMardiya please take a look at [NMAMapDataPrefetcher](https://www.developer.here.com/documentation/ios-premium/3.15/api_reference_jazzy/content/Classes/NMAMapDataPrefetcher.html#/c:objc(cs)NMAMapDataPrefetcher(im)fetchMapDataForBoundingBox:error:)
_-fetchMapDataForBoundingBox:error:_

**Comment by anjanaagrawal35** [comment]
Hello Team,

We need to download the map for offline mode. But the condition is we don't download the whole map [means only download map with zoom level 11]. So that it does not affect more space in the end user's phone.

**Comment by dashchak** [comment]
Hello @anjanaagrawal35, 
HERE SDK uses vector graphics underneath. It means once you download map data for a bounding box, it will be used for all zoom levels of this box

**Comment by anjanaagrawal35** [comment]
Thanks, @dashchak for your valuable feedback.

I have one more question, we can download the map using the radius.
- So is it the same as the bounding box  [work as underneath]? 
- And is there any limitation for the radius[in miles, km, meter]?

**Comment by anjanaagrawal35** [comment]
Team, Can you please help us with the above questions?

**Comment by dashchak** [comment]
> So is it the same as the bounding box [in terms of underneath]?

Correct, it is the same

> And is there any limitation for the radius[in miles, km, meter]?

We have limitation per downloading area. In case it is too big you will receive NMAPrefetchRequestErrorRouteAreaTooBig error. Current prefetch area limit equals 40000000000 square meters. It is private and can be changed in future though. 

> And we can limit the size of downloading maps? like:- low level, mid level and high level resolution with size?

It is not supported. Take a look at NMAMapLoader's
(void)selectDataGroup:(NMAMapDataGroup)dataGroup which impacts package size

> The last thing is there any limitation while defining bounding box?[in size]

Again the limitation is only in areaSize of bounding box. You can use NMAMapLoader which does not have such limits.

**Comment by anjanaagrawal35** [comment]
Ok Thank You.

**Comment by akash0377** [comment]
Hello any one have example code to download map using bounding box, please share.

**Comment by akash0377** [comment]
Hello any one have example code to download map using bounding box, please share.

**Comment by akash0377** [comment]
Hello any one have example code to download map using bounding box, please share.

**Comment by dashchak** [comment]
Please find answer in new thread: https://github.com/heremaps/here-ios-sdk-examples/issues/208
